# Generated by Django 3.0.11 on 2020-12-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placementco', '0002_auto_20201213_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='criteria',
        ),
    ]
