# Generated by Django 3.1.2 on 2020-11-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/student/')),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('cvimage', models.ImageField(blank=True, null=True, upload_to='images/student/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='images/student/')),
                ('session_token', models.CharField(default=0, max_length=10)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
