# Generated by Django 3.1.2 on 2020-11-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cvimage',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
