# Generated by Django 3.1.2 on 2020-11-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
