# Generated by Django 3.1.2 on 2020-11-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyhr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhr',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
