# Generated by Django 3.0.11 on 2020-12-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyhr', '0002_companyhr_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhr',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
