# Generated by Django 3.0.11 on 2020-12-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyhr', '0003_auto_20201213_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhr',
            name='criteria',
            field=models.IntegerField(default=0),
        ),
    ]
