# Generated by Django 3.1.2 on 2020-11-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyCandidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
