# Generated by Django 3.1.2 on 2020-12-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizScore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='score',
            field=models.CharField(max_length=10),
        ),
    ]
