# Generated by Django 3.1.2 on 2020-12-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizScore', '0002_auto_20201201_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='score',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
