# Generated by Django 3.1.2 on 2020-12-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizScore', '0003_auto_20201203_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='correct_answer',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
