# Generated by Django 3.1.2 on 2020-12-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/technology/'),
        ),
    ]
