# Generated by Django 3.1.2 on 2020-11-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=254, unique=True)),
                ('choice1', models.CharField(max_length=50, unique=True)),
                ('choice2', models.CharField(max_length=50, unique=True)),
                ('choice3', models.CharField(max_length=50, unique=True)),
                ('choice4', models.CharField(max_length=50, unique=True)),
                ('answer', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
