# Generated by Django 3.1.2 on 2020-11-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='choice1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='choice2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='choice3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='choice4',
            new_name='option4',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
