# Generated by Django 3.1.2 on 2020-11-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201130_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
