# Generated by Django 3.0.11 on 2020-12-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyhr', '0003_auto_20201213_1235'),
        ('quiz', '0004_auto_20201211_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='companyhr.CompanyHr'),
            preserve_default=False,
        ),
    ]
