# Generated by Django 3.1.2 on 2020-11-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyhr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=50)),
                ('vacancy', models.CharField(max_length=10)),
                ('jobtype', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyhr.companyhr')),
            ],
        ),
    ]
